version: 0.1

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
  build:
    commands:
      - echo Build started on `date`
      - npm install -p
      - npm cd client
      - npm install
      - npm cd ../
      - npm build
      - npm rmdir client
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/messageUtil-1.0.jar
